owner: twocaretcat # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
sites:
  - name: 168421 (168421.xyz)
    url: https://168421.xyz
  - name: Game Maps (game-maps.johng.io)
    url: https://game-maps.johng.io
  - name: Internal Domain Name Calculator for TrueCharts Apps (internal-domain-name-calculator-for-truecharts-apps.johng.io)
    url: https://internal-domain-name-calculator-for-truecharts-apps.johng.io
  - name: Komodo - Mods for Komoot (komodo.johng.io)
    url: https://komodo.johng.io
  - name: Mergist - Online PDF Merger (mergist.johng.io)
    url: https://mergist.johng.io
  - name: My Portfolio (johng.io)
    url: https://komodo.johng.io
  - name: Short End - URL Shortener (l.johng.io)
    url: https://l.johng.io
  - name: Tally - Word Counter (tally.johng.io)
    url: https://tally.johng.io
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.johng.io
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: Status
  introMessage: Uptime and status monitoring for my sites, powered by [Upptime](https://upptime.js.org/).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
workflowSchedule:
  uptime: "0 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
